services:

  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi_data_project1
    restart: always
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=password1234
    volumes:
      - ./data-nifi/flow.xml.gz:/opt/nifi/nifi-current/conf/flow.xml.gz
    user: "0:0" 
    networks:
      - dataproject1

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db
    networks:
      - dataproject1

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: pedro
      ME_CONFIG_BASICAUTH_PASSWORD: pedro 
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - dataproject1
  
  postgres:
    container_name: postgres_data_project1
    image: postgis/postgis:12-3.1 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome01
      POSTGRES_DB: postgres_data_project1
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dataproject1

  pgadmin:
    container_name: pgadmin_data_project1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8082:80
    depends_on:
      - postgres
    networks:
      - dataproject1

  back:
    build: ./back
    container_name: back
    restart: always
    depends_on:
      - mongo
      - postgres
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
      - POSTGRES_URI=postgresql://postgres:Welcome01@postgres:5432/postgres_data_project1
    networks:
      - dataproject1

  front:
    build: ./front
    container_name: front
    restart: always
    depends_on:
      - postgres
      - back
    environment:
      - POSTGRES_URI=postgresql://admin:admin@postgres:5432/postgres_data_project1
    networks:
      - dataproject1

networks:
  dataproject1:
    driver: bridge

volumes:
  postgres:  # Volumen para persistir los datos de PostgreSQL
  pgadmin:   # Volumen para persistir los datos de PgAdmin
  data:      # Volumen para persistir los datos de MongoDB
  data-nifi: # Volumen para persistir los datos de NiFi
