version: '3.5'

services:
  postgres:
    container_name: postgres_container1
    image: postgis/postgis:12-3.1 # Imagen de PostgreSQL con PostGIS
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome01
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"  # Expone PostgreSQL en el puerto 5432
    restart: unless-stopped
    networks:
      - app-valencia

  pgadmin:
    container_name: pgadmin_container1
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"  # Expone PgAdmin en el puerto 5050
    restart: unless-stopped
    networks:
      - app-valencia
  
  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    restart: always
    ports:
      - 8443:8443 #Expone NiFi en el puerto 8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current
      
    user: "0:0"
    networks:
      - app-valencia
  

volumes:
  postgres:  # Volumen para persistir los datos de PostgreSQL
  pgadmin:   #Volumen para persistir los datos de PgAdmin
  nifi_data: #Volumen para persistir los datos de NiFi


networks:
  app-valencia:  # Red compartida para todos los servicios
