FROM python:3.9-slim

# Definir variables de entorno
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Crear directorio de trabajo y usuario no root
WORKDIR /app
RUN useradd -m appuser

# Instalar dependencias del sistema necesarias para PostgreSQL y compilación
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    python3-dev \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar archivos de la aplicación
COPY . /app

# Instalar dependencias de Python (usamos psycopg2-binary en lugar de psycopg2)
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Cambiar usuario para evitar ejecutar como root
USER appuser

# Exponer el puerto de Streamlit
EXPOSE 8501

# Usar Python para ejecutar el script
CMD ["python", "start_services.py"]
